image: node:12.16.1

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm audit fix
    - npm rebuild node-sass
    - CI=false npm run build

deploy-development:
  stage: deploy
  only:
    - firebase
  script:
    - npm install
    - npm audit fix
    - CI=false npm run build
    - npm rebuild node-sass
    - npm install -g firebase-tools
    - firebase use fryz-demo --token $FIREBASE_TOKEN
    - firebase target:apply hosting development fryz-develop --token $FIREBASE_TOKEN
    - firebase deploy --only hosting:development --token $FIREBASE_TOKEN

deploy-production:
  stage: deploy
  only:
    - master
  script:
    - npm install
    - npm audit fix
    - CI=false npm run build
    - npm rebuild node-sass
    - npm install -g firebase-tools
    - firebase use fryz-demo --token $FIREBASE_TOKEN
    - firebase target:apply hosting production fryz-demo --token $FIREBASE_TOKEN
    - firebase deploy --only hosting:production --token $FIREBASE_TOKEN
